package com.fit2081.hongGuan_35100621_nutritrack.data.patient
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a patient entity in the database.
 *
 * This data class is annotated with '@Entity' to
 * inidcate that it represents a table in the database
 * The'tableName' property specifies the name
 * of the table as "patient".
 */
@Entity(tableName = "Patient")
data class Patient(
    /**
     * The unique identifier for the patient.
     * It is automatically generated by the database.
     */
    @PrimaryKey
    val userID: String,

    /**
     * The phone number of the patient.
     */
    val phoneNumber: String,

    /**
     * The name of the patient.
     */
    val name: String?,

    /**
     * The password of the patient
     */
    val password : String?,

    /**
     * The sex of the patient.
     */
    val sex: String,

    /**
     * The HEIFAtotalscore of patient.
     */
    val HEIFAtotalscore : String?,

    /**
     * The vegetable HEIFA score of patient.
     */
    val VegetablesHEIFAscore : String?,

    /**
     * The fruit HEIFA score of patient.
     */
    val FruitHEIFAscore : String?,

    /**
     * The fruit serve size of patient
     */

    val FruitServe: String?,


    /**
     * The fruit variety score of patient
     */

    val FruitVariety: String?,

    /**
     * The grains and cereals HEIFA score of patient.
     */
    val GrainsandcerealsHEIFAscore : String?,

    /**
     * The whole grains HEIFA Score of patient.
     */
    val WholegrainsHEIFAscore : String?,

    /**
     * The meat and alternatives HEIFA score of patient.
     */
    val MeatandalternativesHEIFAscore : String?,

    /**
     * The dairy and alternatives HEIFA score of patient.
     */
    val DairyandalternativesHEIFAscore : String?,

    /**
     * The Water HEIFA score of patient.
     */
    val WaterHEIFAscore : String?,

    /**
     * The unsaturated HEIFA score of patient.
     */
    val UnsaturatedFatHEIFAscore : String?,

    /**
     * The sodium HEIFA score of patient.
     */
    val SodiumHEIFAscore : String?,

    /**
     * The sugar HEIFA score of patient.
     */
    val SugarHEIFAscore : String?,

    /**
     * The Alcohol HEIFA score of patient.
     */
    val AlcoholHEIFAscore : String?,

    /**
     * The discretionary HEIFA score of patient.
     */
    val DiscretionaryHEIFAscore : String?,

    /**
     * The saturated fat HEIFA score of patient.
     */
    val SaturatedFatHEIFAscore : String?,
)



