package com.fit2081.hongGuan_35100621_nutritrack.data.FoodIntake

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import com.fit2081.hongGuan_35100621_nutritrack.data.patient.Patient

/**
 * Represents a patient entity in the database.
 *
 * This data class is annotated with '@Entity' to
 * inidcate that it represents a table in the database
 * The'tableName' property specifies the name
 * of the table as "com.fit2081.hongGuan_35100621_nutritrack.data.FoodIntake.FoodIntake".
 */
@Entity(tableName = "FoodIntake",
    foreignKeys = [
        ForeignKey(
            entity = Patient::class,
            parentColumns = ["userID"],
            childColumns = ["userID"],
            onDelete = ForeignKey.CASCADE  // Delete food intake if patient is deleted

        )
    ],
    indices = [Index(value = ["userID"])]  // Index for faster queries
)
data class FoodIntake(
    /**
     * The unique identifier for the food intake.
     * It is automatically generated by the database.
     */
    @PrimaryKey(autoGenerate = true)
    val questionnaireID: Int = 0,

    val userID : String,

    /**
     * Food categories user eats.
     */
    val fruits : Boolean,
    val vegetables : Boolean,
    val grains : Boolean,
    val redMeat : Boolean,
    val seafood : Boolean,
    val poultry : Boolean,
    val fish : Boolean,
    val eggs : Boolean,
    val nutsOrseeds : Boolean,

    /**
     * User's Persona
     */
    val persona : String,

    /**
     * User's eating timing habits
     */
    val biggestMeal : String,
    val sleepTime : String,
    val wakeTime : String
)